# Generated by Django 5.0.1 on 2024-09-23 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='adverts.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='response',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='adverts.advert', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='response',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='adverts.category'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['-time_create'], name='adverts_adv_time_cr_0d88d8_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['-time_create'], name='adverts_res_time_cr_8503bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'category')},
        ),
    ]
